version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/infra/terraform/aws"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/infra/terraform/posthog"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/infra/uptime-kuma/monitor-runner"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/images/alertmanager"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/images/caddy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/images/grafana"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/images/mcp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/images/minio"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/images/tailscale"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/images/vector"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/images/vmalert"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/images/web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/images/worker"
    schedule:
      interval: "weekly"
