apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: victoriametrics
    access: proxy
    url: http://${APP_VICTORIA_METRICS_HOST}:8428
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      alertmanagerUid: alertmanager
      prometheusType: Prometheus
      timeInterval: 15s
      cacheLevel: Low

  - name: VictoriaLogs
    type: victoriametrics-logs-datasource
    uid: victorialogs
    access: proxy
    url: http://${APP_VICTORIA_LOGS_HOST}:9428
    editable: false
    jsonData:
      logLevelRules:
        - field: level
          operator: regex
          value: error|fatal
          level: error
          enabled: true
        - field: level
          operator: regex
          value: warn|warning
          level: warning
          enabled: true
        - field: level
          operator: regex
          value: info
          level: info
          enabled: true

  - name: VictoriaTraces
    type: jaeger
    uid: victoriatraces
    access: proxy
    url: http://${APP_VICTORIA_TRACES_HOST}:10428/select/jaeger
    editable: false
    jsonData:
      nodeGraph:
        enabled: true
      spanBar:
        type: Duration

  - name: Alertmanager
    type: alertmanager
    uid: alertmanager
    access: proxy
    url: http://${APP_ALERTMANAGER_HOST}:9093
    editable: false
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false
